# Generated by Django 2.2.28 on 2025-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
